---
skip_tags: true

skip_commits:
  files:
    - '*.md'
    - '*.yml.default'
  message: /\[minor\]/

image: ubuntu

environment:
  CLOUDBOX_PATH: "/home/appveyor/cloudbox"
  COMMUNITY_PATH: "/home/appveyor/projects/community"

init:
  - sh: curl -s https://cloudbox.rocks/dep.sh | sudo -H sh
  - sh: curl -s https://cloudbox.rocks/repo.sh | bash

install:
  - sh: cd ${COMMUNITY_PATH}
  - sh: sudo ansible-playbook community.yml --syntax-check
  - sh: sudo ansible-playbook "${CLOUDBOX_PATH}/cloudbox.yml" --tags core --skip-tags settings --extra-vars '{"continuous_integration":true}'
  - sh: sudo ansible-playbook community.yml --tags airsonic
  - sh: sudo ansible-playbook community.yml --tags calibre-rdp
  - sh: sudo ansible-playbook community.yml --tags calibre-web
  - sh: sudo ansible-playbook community.yml --tags lazylibrarian
  - sh: sudo ansible-playbook community.yml --tags monitorr
  - sh: sudo ansible-playbook community.yml --tags logarr
  - sh: sudo ansible-playbook community.yml --tags radarr1080
  - sh: sudo ansible-playbook community.yml --tags sonarr1080
  - sh: sudo ansible-playbook community.yml --tags sonarrv3
  - sh: sudo ansible-playbook community.yml --tags mylar
  - sh: sudo ansible-playbook community.yml --tags deluge
  - sh: sudo ansible-playbook community.yml --tags mellow

matrix:
  fast_finish: true

# to disable automatic builds
build: off
