#########################################################################
# Title:         Cloudbox Community: Telly 1.1 Role                     #
# Author(s):     EnorMOZ, Desimaniac, chazlarson                        #
# URL:           https://github.com/Cloudbox/Community                  #
# Docker Image:  tellytv/telly:dev-ffmpeg                               #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: tellydev

- name: "Assert that all Telly related settings are filled in."
  assert:
    that:
      - (tellydev.m3u_url is defined) and (tellydev.m3u_url is not none) and not (tellydev.m3u_url | trim == '') and (tellydev.m3u_url != "/opt/telly/file.m3u or URL2M3U")
      - (tellydev.epg_url is defined) and (tellydev.epg_url is not none) and not (tellydev.epg_url | trim == '') and (tellydev.epg_url != "/opt/telly/file.xml or URL2XML")
      - (tellydev.streams is defined) and (tellydev.streams is not none) and not (tellydev.streams | trim == '')
    msg: "You must specify the Telly settings in 'settings.yml'"

- name: Stop and remove any existing container
  docker_container:
    name: tellydev
    state: absent

- name: Create telly directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "/opt/tellydev"

- name: Check config exists
  stat:
    path: "/opt/tellydev/telly.config.json"
  register: tellydev_config

- name: Do following tasks when config does not exist
  block:

  - name: Import default config
    template:
      src: telly.config.json.js2
      dest: /opt/tellydev/telly.config.json
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0775
      force: yes

  when: not tellydev_config.stat.exists

- name: Create and start container
  docker_container:
    name: tellydev
    image: "tellytv/telly:dev-ffmpeg"
    pull: yes
    user: "{{uid}}:{{gid}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/tellydev/:/etc/telly/"
    env:
      VIRTUAL_HOST: "tellydev.{{domain}}"
      VIRTUAL_PORT: 6077
      LETSENCRYPT_HOST: "tellydev.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - tellydev
    purge_networks: yes
    restart_policy: always
    state: started
